[package]
edition = "2021"
name = "invoke_derive"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
convert_case = "0.4.0"
quote = "1.0.9"
syn = {version = "1", features = ["full"]}
uuid = {version = "1.1", features = ["v4"]}
